name: Android CI

on: [push,pull_request]
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Prepare App
      run: |
        mkdir -p ${{ github.workspace }}/apk/
        for file in `find ~ -name "*.apk" -print`; do
          mv "$file" ${{ github.workspace }}/apk/
        done
    - name: Upload App To Artifact
      uses: actions/upload-artifact@v3
      with:
        name: com.abc.test.apk
        path: ${{ github.workspace }}/apk/*